# An Emasculation Epidemic

------------------------------------------------------------------------

> Numbing the pain for a while will make it worse when you finally feel it.
>
> --- Albus Dumbledore, *Harry Potter and the Goblet of Fire*

  Throughout time men have had a distinct purpose in every society. They were the leaders, providers, mentors, and role-models. However, in modern society these norms have been stood on their head. Even before the many feminist movements the process of emasculating men had already begun.\
\
  The first pillar of a strong man to be destroyed was that of morality: specifically, religion. When the industrial revolution was on it's heels religion was beginning to be replaced by *science.* However, this science was the distinct polar opposite of it's predecessor which went by the same name. While the science that was studied for thousands of years was the study of God's creation, it radically morphed into the *study of*. This once cooperative link between religion and science turned into a secular mess of `atheism`. Modern science rejects all religion and instead seeks irrational and illogical conclusions with no foundation and no conclusive evidence. Instead of seeking truth, the goal of modern science is to invalidate and smear Christianity. The biggest issue with science is that is is treated as a religion on its own. However, no religion can be firm if it is simply ever-changing as new theories emerge. This weak and unfounded study called science, has seeped into every bit of modern life. Slowly, but ever-surely, it has seemingly toppled *truth* in favor of `moral relativism` and subjectivity. Men are now waking up to the sad reality that is modern society. A society where opinion rules, truth fails, and moral decay begins. It is truly a world of depression and loneliness.\

> The truth: It is a beautiful and terrible thing, and should therefore be treated with caution.
>
> --- Albus Dumbledore, *Harry Potter and the Philosopher's Stone*

\
  Shortly after the decay of religion was the decay of `virtue`. Men were encouraged to be weak and blamed for any strength they showed. While this is now outright spoken, in the early 1900s these facts were hidden within habits and entertainment. Corporations in America found that addictions were profitable and that certain foods and activities lowered the `testosterone` of men. Some of these included tobacco, micro-plastics, harmful chemicals, pornography, atheism, and propagandic films. Throughout the years the next wave of emasculation attempts came in the forms of splitting the nuclear family, encouraging female independence, and sexual perversion (gender ideology and `hookup culture`).

## Dopamine Dependency

------------------------------------------------------------------------

  "Back in my day" is a term we often hear from our parents seeking to softly teach or instill concepts of perceived higher morality. What if I told you that we should not be scared of these assessments. Rather, we ought to give it real thought, even if our natural intuition is to immediately dismiss it. Back in the day of our grandparents, the emasculation of men really became clear. A new generation of people were raised without morals and without any concept for authority. It is the context of every period of history which helps us to consider the outcome of morality. Morals are black and white, ever changing and never ending. But they can sound far more `progressive` or `conservative` depending on the time in which they are pressed upon.

\
 A concept which I would like you to weigh is that of the trend of using your phone as an extension of your very mind. I concede that I have rarely thought of it like this, but now that I do, it worries me. It is objective that technological advances like electronics and computers have made modern life more efficient. However, I believe we have suffered an untold consequence because of this trade for efficiency. We have traded simplicity for efficiency, a trade which I believe to be very unequal.

### Simplicity: Our Original State (WIP)

------------------------------------------------------------------------

> Nature does nothing in vain when less will serve; for Nature is pleased with simplicity and affects not the pomp of superfluous causes.
>
> --- Sir Issac Newton, *Principia Mathematica*

  Original state: simplicity and joy with the Lord \| Natural state: complexity and rebellion

## The Monetization of Lust

------------------------------------------------------------------------

  Every single day we are bombarded by lustful content that seeks to monetize our carnal lust. While there is no excuse to look on a women with lust, the authorities of this world understand the power in which lust has over us. The passion of sexuality which God has granted to each of us is a gift which should be shared in marriage. However, the authorities of this world use this pure passion and estrange it to lure us into evil situations. Lustful content will always be around because a supply for sex and titillation will never cease; it is a never ending battle in which we wage war against every day. You are not alone, no matter who you are, we all struggle against this grave sin. It is up to us as men to step up and deny lust and to show the world what a pure marriage looks like and the joys which radiate from it.

### Pornography

------------------------------------------------------------------------

> It was maddening how beautiful she was, but did that make the rest of her any less real?
>
> --- *If We Were Villains*

  Pornography directly undermines the way we view women and sex. When we view pornography we are not only committing a disgusting act alone, we are actively objectifying women as sexual objects to be used and so often abused. This completely undermines the many purposes of sex. God tells us in the Bible for our own safety what sex is for as well as how and when it is appropriate (**See Appendix I: Sex is Sacred**). Pornography actively makes you less of a man and taints your intuition for justice. Below are the many reasons why pornography is detrimental. These effects are exponentially more detrimental in adolescents.

I.  Pornography Emasculates

II. Pornography Objectifies and Incites Fetishes and Unspeakable Acts

III. Pornography Numbs Sexual Receptors

IV. Pornography Promotes Superficial Expectations of Sex

V.  Pornography Incites Depression and Social Anxiety

VI. The Pornography Industry Monetizes Sex Trafficking

### Gender Perversion (WIP)

------------------------------------------------------------------------

> That which is not good for the swarm, neither is it good for the bee.
>
> --- Marcus Aurelius, *Meditations*

 

### Justification of Depravity (WIP)

------------------------------------------------------------------------

> Dear brother, you cannot prevent the birds from flying in the air over your head, but you can prevent them from building a nest in your hair.
>
> --- Martin Luther, *Explanation of the Lord's Prayer*

 For thousands of years it has been accepted that men are lustful creatures and that their lust must be quenched. In ancient times, this was fulfilled by concubines and sex slaves. These people were forced into sexual servitude for the satisfaction of their masters. They further justified their actions by implementing this sexual deviancy into worship of their gods. We see that this type of "worship" was practiced by cultures from the eastern shores of India to the sparkling temples of Greece. In modern times, culture and even doctors claim that sexual deviancy (fornication, masturbation, and lust) is natural and even healthy for people to partake in. However, that does not stop them from feeling the guilt after their perverted acts. A [recent study](https://pubmed.ncbi.nlm.nih.gov/30358432/ "Pornography Consumption, Modality and Function in a Large Internet Sample") shows that 91.5% of men and 60.2% of women have watched pornography in the last month. This statistic alone qualifies these percentages as being adults addicted to pornography.

 We in the West like to think of ourselves as *sophisticated* and *civilized* but we are no more than intelligent dogs. We still allow our carnal passions to run rampant. We justify evil deeds in the name of happiness, or health, or maybe even *necessity*. After all, the common argument is that there will be less rapists if they are all watching pornography.

## The Extermination of Exercise

------------------------------------------------------------------------

> It is a shame for a man to grow old without seeing the beauty and strength of which his body is capable.
>
> --- Socrates, *Xenophon’s Memorabilia*

  Every person is built with the innate instinct to survive. It has how we as humans have survived thousands of years on a planet full of threats. Throughout all time, we see that the wealthy brush off core disciplines in favor of `voluptuous` living. These typically included hard work, service, exercise, and even honor. For a man, `testosterone` is the biggest component of his physical body. Reducing exercise and increasing worthless pleasures often diminishes such ample testosterone levels. It is difficult to correlate any meaningful facts between obesity and depression with any other symptoms. This is because of the drastic change in lifestyle the west has incurred. Large cities, pollution, plastics, urbanization, industrialization, and isolation have all come to affect our day to day lives. The unfortunate truth of our lives is that large corporations profit off our sickness. They entrench us in a cycle from the day we are born till the day we die. The cycle: listen, do not think, the experts are always correct. Skepticism of *non qualified* people is treated as a child's questioning of their parents. What they want is for you not to own anything and to be happy.

 Lounging around, neglecting exercise, emphasizing stress, and overeating are all problems which the average American faces. The key thing to keep in mind is that when doing these things you relinquish your rights to your body to the corporation who feeds, entertains, stresses, and medicates you. They want to use and abuse you. Break out of this cycle and take your life into your own hands. Wake up earlier and go to the gym. Break that stigma that you could never be a runner. Go enroll in a sports league. These are all healthy things that not only support your physical health but will also overflow benefits into the rest of your life. You will notice less brain-fog, a more productive attitude, better sleep, a happier demeanor, and a healthier and fit body. We often become too shortsighted to think about the future. One future I often think about is my physical health when I grow old. Will I have dementia and be laying on my deathbed for five years, or will I be clear thinking and squatting to retrieve my grandchildren. These are the kinds of questions that ought to spur you in your exercise.

 Exercise does not have to be a mentally stressful activity. You should start slow and work on building a solid weekly routine. A bulletproof plan for both the youthful and the aging is a hybrid workout regime. This regime includes activities like running / walking, biking, sports, weightlifting, and specialized mobility work. Train like our ancestors **lived** in their nomadic lifestyles. The plan is the same for both the youthful and the aging, build cardiovascular health, strong and enduring muscles, flexible and mobile joints, a bulletproof and tactical mind, and a joyful spirit. Playing sports is especially important because of the camaraderie between players. It also helps you to retain your neural pathways by using your brain to make quick decisions. This will help the mind to stay fit while you keep your body in order.

 It is never to late to start.

## Generation: Isolated (WIP)

------------------------------------------------------------------------

 

### Forever Gaming

------------------------------------------------------------------------

 

### Social Media: Depravity Hub

------------------------------------------------------------------------

 
