# References

  The collection of bolded definitions and concepts throughout the book.

------------------------------------------------------------------------

## Definitions for Words and Concepts

1.  **Atheism**

    > Rejection of traditional religion, sometimes referred to as disbelief in the supernatural. Many instead seek validation within themselves or various social movements.

2.  **Hookup Culture**

    > An overall belief by a people group that sexual intimacy can (and often should) be enjoyed frequently outside of marriage without consequence. It also includes the belief that sexual intimacy is not particularly special. More specifically that it is simply a fun use of time or a good way to get to know someone.

3.  **Moral Relativism**

    > The belief that morals (spiritual principles) are subjective. Many would deny that morals are spiritual at all instead arguing that they are learned from their upbringing and influenced by culture.

4.  [**Virtue**](https://www.merriam-webster.com/dictionary/virtue "Virtue Definition")

    > Morally good behavior or character.

5.  **Testosterone**

    > The primary male sex hormone which plays a significant role in the mental fortitude and physical stature of a man.

6.  [**Voluptuous**](https://www.merriam-webster.com/dictionary/voluptuous "Voluptuous Definition")

    > Full of delight or pleasure to the senses **:** conducive to or arising from sensuous or sensual gratification.

7.  WIP

## Resources

[YourBrainOnPorn](https://www.yourbrainonporn.com/research/ "More Research on the Effects of Pornography")

- An extensive resource which provides help for those seeking to quit pornography. They also compile and commentate legitimate scientific articles. The research section contains these said articles covering almost any question that may be asked.
