---
title: "Manhood: Returning to Our Roots"
author: "B. Tener"
description:
url:
github-repo:
cover-image:
apple-touch-icon:
apple-touch-icon-size: 120
favicon:
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    config:
     fontsettings:
       theme: night
       family: serif
---

# Preface

------------------------------------------------------------------------

> Waste no more time arguing about what a good man should be. Be one.
>
> --- Marcus Aurelius, *Meditations*

  Often times I think about my past and what I could have done better. However, the past has made me who I am. The real question is, how can I help people from going down that same dark and depressing road. This book is a collaboration effort by men who have endured the worst that our society has to offer. We have overcome our many trials through years of grueling fighting and experimentation. This book is a project which has been brewing for many years and is teeming with heaps of wisdom. We seek to help those who have been tactfully exploited by our society in hopes of restoring them into strong men once again. In retrospect, to have a resource like this book would have been life changing. Whether I would have read it and taken seriously is another story. However, the lack of material on this subject other than the countless YouTube videos is astonishing. This book is not meant to bash these YouTubers, they are doing God's work. On the contrary, the point of this book is to be the foundational guide for a man living in our modern world. For some, this book will be the ultimate resource that they have been searching for. Others may not take it seriously at all and while saddening, it is their choice. However, with anything, a skeptical and brutally honest attitude is required to truly understand the content and make a judgement call. The ability to critically think by isolating the truth from the abundant falsities of this world is the first skill required in becoming a strong man.

> The content of your character is your choice. Day by day, what you choose, what you think and what you do is who you become.
>
> --- Heraclitus, *Peri Physeos*

  As men, we must be prepared to separate the wheat from the chaff **every single day.**

## Authorities

------------------------------------------------------------------------

  Throughout this resource you will see many authors quoted. They may be philosophers, saints, authors, ancient writers, and fictional characters. The basis for this book is grounded in the truth of the Bible. Some may scoff at this statement. However, morality (discussed later) is an essential part of being a man. Anything can be anything without Truth. For those who are opposed to the Bible or skeptical of it's usage, read the whole book. The authors intentions are not to force religion down your throat, there is no use in that. Instead, we seek to use the Bible as the ultimate foundation and basis for the views discussed later. At the end of this book, whether you decide to follow the God of the Bible is a choice only **you** can make.

## References

------------------------------------------------------------------------

  Throughout the book, definitions will be highlighted and linked to their corresponding definition in the "Definitions" section. References to unlisted sources (studies, videos, podcasts, websites, etc.) will be linked for easy access. When available, primary sources will be used to further reinforce the truth with which we seek to share.

## Acknowledgements

------------------------------------------------------------------------

  This book is a labor of love which has been developed through many years of research and anecdotal experiences. I want to personally thank Dynel and Caleb for their deep thoughts and questions which have contributed to the content of this book. Thank you to all the contributors who made this book possible and the many lives that have and will be changed for the better because of it.\
